apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilebanking-rs
  namespace: default
  labels:
    app: bank
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: cont1
        image: reyadocker/internetbankingrepo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobilebankingservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: bank
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31433
